# Form implementation generated from reading ui file '.\ui\enter_values.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_enter_values(object):
    def setupUi(self, Dialog_enter_values):
        Dialog_enter_values.setObjectName("Dialog_enter_values")
        Dialog_enter_values.resize(564, 328)
        Dialog_enter_values.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(81, 0, 135, 255), stop:0.427447 rgba(41, 61, 132, 235), stop:1 rgba(155, 79, 165, 255));\n"
"font-family: Liberation Serif;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_enter_values)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_details = QtWidgets.QLabel(parent=Dialog_enter_values)
        self.label_details.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.label_details.setObjectName("label_details")
        self.horizontalLayout.addWidget(self.label_details)
        self.textEdit_count_details = QtWidgets.QTextEdit(parent=Dialog_enter_values)
        self.textEdit_count_details.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.textEdit_count_details.setObjectName("textEdit_count_details")
        self.horizontalLayout.addWidget(self.textEdit_count_details)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label__machienes = QtWidgets.QLabel(parent=Dialog_enter_values)
        self.label__machienes.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.label__machienes.setObjectName("label__machienes")
        self.horizontalLayout_2.addWidget(self.label__machienes)
        self.textEdit_count_machienes = QtWidgets.QTextEdit(parent=Dialog_enter_values)
        self.textEdit_count_machienes.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.textEdit_count_machienes.setObjectName("textEdit_count_machienes")
        self.horizontalLayout_2.addWidget(self.textEdit_count_machienes)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_min = QtWidgets.QLabel(parent=Dialog_enter_values)
        self.label_min.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.label_min.setObjectName("label_min")
        self.horizontalLayout_3.addWidget(self.label_min)
        self.textEdit_min = QtWidgets.QTextEdit(parent=Dialog_enter_values)
        self.textEdit_min.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.textEdit_min.setObjectName("textEdit_min")
        self.horizontalLayout_3.addWidget(self.textEdit_min)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_max = QtWidgets.QLabel(parent=Dialog_enter_values)
        self.label_max.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.label_max.setObjectName("label_max")
        self.horizontalLayout_4.addWidget(self.label_max)
        self.textEdit_max = QtWidgets.QTextEdit(parent=Dialog_enter_values)
        self.textEdit_max.setStyleSheet("background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"font-weight: bold;\n"
"font-size: 20pt;")
        self.textEdit_max.setObjectName("textEdit_max")
        self.horizontalLayout_4.addWidget(self.textEdit_max)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_ok = QtWidgets.QPushButton(parent=Dialog_enter_values)
        self.pushButton_ok.setEnabled(True)
        self.pushButton_ok.setStyleSheet("QPushButton {\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"text-align: center;\n"
"background-color: rgba(255, 255, 255, 30);\n"
"border: 1px solid rgba(255, 255, 255, 40);\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 255, 255, 40);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 255, 255, 70);\n"
"}")
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.verticalLayout.addWidget(self.pushButton_ok)

        self.retranslateUi(Dialog_enter_values)
        QtCore.QMetaObject.connectSlotsByName(Dialog_enter_values)

    def retranslateUi(self, Dialog_enter_values):
        _translate = QtCore.QCoreApplication.translate
        Dialog_enter_values.setWindowTitle(_translate("Dialog_enter_values", "Ввод данных"))
        self.label_details.setText(_translate("Dialog_enter_values", "Количество деталей"))
        self.label__machienes.setText(_translate("Dialog_enter_values", "Количество станков"))
        self.label_min.setText(_translate("Dialog_enter_values", "Минимальное значение"))
        self.label_max.setText(_translate("Dialog_enter_values", "Максимальное значение"))
        self.pushButton_ok.setText(_translate("Dialog_enter_values", "Ок"))
